### ISSUE TITLE
What if my fragment is already `extends` another fragment?

### ISSUE THREAD

**Issue by littlehome-eugene** [hudl/react-native-android-fragment#10]
I have a fragment which extends some `MyBaseFragment`

should I make MyBaseFragment extends `ReactFragment` ? 
Are there other options?

**Comment by jpshelley** [comment]
@littlehome-eugene as of now you will have to use inheritance and extend from `ReactFragment`. So your `MyBaseFragment` would also have to extend from it.

Ideally we would like to use some form of composition instead of inheritance - but we chose inheritance to better align with the main React Native code.

[Official ReactActivity example](https://github.com/facebook/react-native/blob/master/RNTester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterActivity.java#L21)

It is unlikely that we would change this pattern unless Facebook did as well in the main repo.
